name: Deploy to Mac Mini

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Mac Mini
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAC_MINI_HOST }}
          username: ${{ secrets.MAC_MINI_USERNAME }}
          key: ${{ secrets.MAC_MINI_SSH_KEY }}
          script: |
            cd /path/to/project
            git pull
            npm install
            npm run build
            pm2 restart back
